"""Add organization audit retention policies

Revision ID: eeba34146645
Revises: a809b1740bcd
Create Date: 2026-09-30 10:22:10.203707

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eeba34146645"
down_revision: str | Sequence[str] | None = "a809b1740bcd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_audit_retention_policies",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("security_audit_days", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "security_audit_days IS NULL OR "
            "(security_audit_days >= 30 AND security_audit_days <= 3650)",
            name=op.f("ck_organization_audit_retention_policies_security_audit_days_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_audit_retention_policies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "organization_id", name=op.f("pk_organization_audit_retention_policies")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_audit_retention_policies")
    # ### end Alembic commands ###
